# Generated by Django 5.1.1 on 2024-09-17 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mdp', models.CharField(max_length=128)),
                ('pseudo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoadTrip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publique', models.BooleanField(default=False)),
                ('etapes', models.CharField(max_length=255)),
                ('depart', models.DateField()),
                ('nbjour', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('like', models.BooleanField(default=False)),
                ('roadtrip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.roadtrip')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('roadtrip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.roadtrip')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.utilisateur')),
            ],
        ),
    ]
