# Generated by Django 5.1.3 on 2024-12-16 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mdp', models.CharField(max_length=128)),
                ('pseudo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoadTrip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publique', models.BooleanField(default=False)),
                ('etapes', models.JSONField(default=list)),
                ('depart', models.DateTimeField()),
                ('nbjour', models.IntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.utilisateur')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('like', models.BooleanField(default=False)),
                ('roadtrip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.roadtrip')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('roadtrip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.roadtrip')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.utilisateur')),
            ],
        ),
    ]
