# Generated by Django 5.1.3 on 2024-12-17 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadtrip',
            options={'ordering': ['-created_at'], 'verbose_name': 'Road Trip', 'verbose_name_plural': 'Road Trips'},
        ),
        migrations.AddField(
            model_name='roadtrip',
            name='nom',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du voyage'),
        ),
        migrations.AddField(
            model_name='roadtrip',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix total'),
        ),
        migrations.AddField(
            model_name='roadtrip',
            name='retour',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de retour'),
        ),
        migrations.AlterField(
            model_name='roadtrip',
            name='depart',
            field=models.DateTimeField(verbose_name='Date de départ'),
        ),
        migrations.AlterField(
            model_name='roadtrip',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description du voyage'),
        ),
        migrations.AlterField(
            model_name='roadtrip',
            name='etapes',
            field=models.JSONField(default=list, verbose_name='Étapes du voyage'),
        ),
        migrations.AlterField(
            model_name='roadtrip',
            name='nbjour',
            field=models.PositiveIntegerField(default=1, verbose_name='Nombre de jours'),
        ),
        migrations.AlterField(
            model_name='roadtrip',
            name='publique',
            field=models.BooleanField(default=False, verbose_name='Voyage public'),
        ),
        migrations.AlterField(
            model_name='roadtrip',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadtrips', to='App.utilisateur', verbose_name='Voyageur'),
        ),
    ]
